
export default {
  SET_TOKEN: 'SET_TOKEN', // 保存token
  SET_SYSTEM_INFO: 'SET_SYSTEM_INFO', // 保存系统信息（设备参数等）
  SET_USER_INFO: 'SET_USER_INFO', // 用户信息
  SET_WX_SESSION_KEY: 'SET_WX_SESSION_KEY', // 用户信息
  SET_NEED_TO_CHECK_LOGIN: 'SET_NEED_TO_CHECK_LOGIN',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_BASE_INFO: 'SET_BASE_INFO',
  SET_CART_SKUIDS: 'SET_CART_SKUIDS',
  SET_ADDRESS_PACS_CODE: 'SET_ADDRESS_PACS_CODE', // 识别地址
  SET_ADDRESS_ZIP_CODE: 'SET_ADDRESS_ZIP_CODE', // 识别地址管理
  SET_INSIDE_SHOPPING_ACTIVITY: 'SET_INSIDE_SHOPPING_ACTIVITY', // 设置内购活动
  SET_CART_STATUS_REFRESH: 'SET_CART_STATUS_REFRESH', // 设置购物车列表刷行状态
  SET_INVITATION_CODE: 'SET_INVITATION_CODE', // 设置邀请码
  SET_POSTER_STRATEGY: 'SET_POSTER_STRATEGY', // 设置 海报 - 战略海报
  SET_POSTER_RECOMMEND: 'SET_POSTER_RECOMMEND', // 设置 海报 - 推荐海报
  SET_WX_USER_INFO: 'SET_WX_USER_INFO', // 设置 微信用户信息
  SET_CUSTOMER_USER_INFO: 'SET_CUSTOMER_USER_INFO', // 设置 客户用户信息
  SET_ORDER_SUM: 'SET_ORDER_SUM', // 设置 推荐官比较金额
  POSTER_TEMPLATE: 'POSTER_TEMPLATE', // 设置 海报对象
  SET_COUPON_LIST_ID: 'SET_COUPON_LIST_ID' // 设置 海报对象
}
