// bus事件名称
module.exports = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CHANGE_ORDER_STATUS: 'CHANGE_ORDER_STATUS', // 订单状态改变
  CART_STATUS_REFRESH: 'CART_STATUS_REFRESH', // 购物车状态更新
  COUPON_STATUS_REFRESH: 'COUPON_STATUS_REFRESH', // 优惠券状态更新
  COUPON_ID_STATUS_REFRESH: 'COUPON_ID_STATUS_REFRESH', // 优惠券id更新
  COUPON_CAR_REFRESH: 'COUPON_CAR_REFRESH' // 购物车优惠券更新
}